[[redirects]]
  from = "/crm_k0J2A0h"
  to = "https://sjv52.mjt.lu/nl3/LaRyI16eN4bJycGfUxRV4g?hl=en"
  status = 302

[[redirects]]
  from = "amd_vse5Dw3g"
  to = "https://drive.google.com/file/d/1Cx2MS7mbLFW9UDP1OWer8zeyrVZT1njV/view?usp=sharing"
  status = 302

[[redirects]]
  from = "azf_5sgjuy0z"
  to = "https://drive.google.com/file/d/18CSDAyG9U3S9nEFnCOXaWLL49yFruvbW/view?usp=sharing"
  status = 302

[[redirects]]
from = "/raf_9W11dw9"
to = "https://677ee5b4b818b800a237d108-raf-demo.netlify.app/"
status = 302

[[redirects]]
from = "/fle_1L6dr4J"
to = "https://fletch.ooo"
status = 302

[[redirects]]
from = "/bd_SIJsD38a"
to = "https://birddoginteractive.com"
status = 302

[[redirects]]
from = "/svm_d0jXpsV5"
to = "/portfolio/decks/4673-surface_holiday_fy22_2021-08-05.pdf"
status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

